name: DP-LASS
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py310h06a4308_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.1.55=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-version=12.8=3
  - cuda-visual-tools=11.6.1=0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.13.1.3=0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.13.1.3=0
  - libcufile-dev=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcurand-dev=10.3.9.90=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2025.1.1.2=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.23.5=py310hd5efca6_0
  - numpy-base=1.23.5=py310h8e6c178_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hcea889d_0
  - pip=25.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - pytorch=1.13.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - setuptools=72.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tbb-devel=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.13.1=py310_cu116
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.3.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.5.2
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - alembic==1.15.2
      - anyio==4.8.0
      - arrow==1.3.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - audioread==3.0.1
      - beautifulsoup4==4.13.3
      - blessed==1.20.0
      - boto3==1.37.11
      - botocore==1.37.11
      - bottle==0.13.2
      - braceexpand==0.1.7
      - cachetools==5.5.2
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorlog==6.9.0
      - contourpy==1.3.1
      - croniter==1.3.15
      - cycler==0.12.1
      - dateutils==0.6.12
      - decorator==5.2.1
      - deepdiff==7.0.1
      - editor==1.6.6
      - exceptiongroup==1.2.2
      - fastapi==0.88.0
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2023.12.2
      - ftfy==6.1.1
      - future==1.0.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - greenlet==3.2.0
      - grpcio==1.54.0
      - h11==0.14.0
      - h5py==3.8.0
      - hdbscan==0.8.40
      - huggingface-hub==0.29.2
      - idna==3.10
      - inquirer==3.4.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning==2.0.0
      - lightning-cloud==0.5.33
      - lightning-utilities==0.8.0
      - llvmlite==0.41.1
      - mako==1.3.10
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msclap==1.3.2
      - msgpack==1.0.5
      - msgpack-numpy==0.4.8
      - multidict==6.1.0
      - narwhals==1.35.0
      - networkx==3.4.2
      - numba==0.58.1
      - oauthlib==3.2.2
      - optuna==4.3.0
      - optuna-dashboard==0.18.0
      - ordered-set==4.1.0
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.14.0
      - platformdirs==4.3.6
      - plotly==6.0.1
      - pooch==1.8.2
      - propcache==0.3.0
      - protobuf==6.30.0
      - psutil==6.1.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==1.10.21
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pyloudnorm==0.1.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-lightning==2.0.1.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - readchar==4.2.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rsa==4.9
      - runs==1.2.2
      - s3transfer==0.11.4
      - safetensors==0.5.3
      - scikit-fuzzy==0.5.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - sqlalchemy==2.0.40
      - starlette==0.22.0
      - starsessions==1.3.0
      - sympy==1.13.1
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.5.0
      - tokenizers==0.13.3
      - torch==2.1.2
      - torchlibrosa==0.1.0
      - torchmetrics==1.6.2
      - torchvision==0.16.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.28.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uvicorn==0.34.0
      - wcwidth==0.2.13
      - webdataset==0.2.48
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.1.3
      - wget==3.2
      - xmod==1.8.1
      - yarl==1.18.3

